# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6794a6a3cc76944e7fc04cb08583ea2c3b17fb88b8f7ffcbf13734026aaa1b472f605c6011d984b8d3de2df1ef29e68e4dd33d7586e3d85d756c5a2d0e041ccc
  twilio_account_sid:  <%= ENV.fetch("TWILIO_ACCOUNT_SID", "AC647fadada94758c9d95a7d55624f9d60") %>
  twilio_auth_token:  <%= ENV.fetch("TWILIO_AUTH_TOKEN", "fd8fea7a9a2ad42ba10b31d535197649") %>
  twilio_phone_number:  <%= ENV.fetch("TWILIO_PHONE_NUMBER", "+18125787965") %>

test:
  secret_key_base: 0095b33a6d53297994c1129f742c783249829f5984207e944277a20b0fb012d799c4db443edd6200fd83f70c3ecaf6433241cc0787c4a680dfdc5bea762e7b27

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
